name: ChatUnlimited
version: 1.2.0
main: org.felixdev.chatunlimited.Chatunlimited
api-version: "1.21"
description: Chat Unlimited with formats, join/quit messages, MOTD and antispam
author: FelixDev
website: https://vishubistudio.net
softdepend: [PlaceholderAPI]

commands:
  chatunlimited:
    description: Comandos principales de ChatUnlimited
    usage: /<command> <reload|motd|antispam|test|info>
    aliases: [cu, chatu]

permissions:
  chatunlimited.reload:
    description: Permiso para recargar la configuración
    default: op
  chatunlimited.motd:
    description: Permiso para gestionar MOTD
    default: op
  chatunlimited.antispam:
    description: Permiso para gestionar antispam
    default: op
  chatunlimited.bypass.antispam:
    description: Bypass del sistema antispam
    default: op
  chatunlimited.*:
    description: Todos los permisos
    default: op
    children:
      chatunlimited.reload: true
      chatunlimited.motd: true
      chatunlimited.antispam: true
      chatunlimited.bypass.antispam: true