chat:
  format: "{prefix} {player} &8» &f{message}"
  per-world: true
  hover:
    - "&bInformación de &f{player}"
    - "&7Rango: &f{rank}"

messages:
  join: "&8[&a+&8] &7Bienvenido, &f{player}"
  quit: "&8[&c-&8] &7{player} ha salido"
  # Este es el MOTD que verán en su chat al entrar:
  motd-chat:
    - "&7&m---------------------------------------"
    - "               &b&lServer"
    - "  &f¡Bienvenido de nuevo, &e{player}&f!"
    - "   &7Actualmente hay &a{online} &7jugadores."
    - "&7&m---------------------------------------"
  no-permission: "&cNo tienes permiso."
  reload-success: "&a¡Configuración recargada!"

antispam:
  enabled: true
  cooldown-time: 2
  cooldown-message: "&c¡Espera {time}s!"